import Head from 'next/head'
import Header from '../component/Header'
import Navbar from '../component/Navbar'
import Result from '../component/Result'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* HEADER */}
      <Header/>
      {/* NAVBAR */}
      <Navbar/>
      {/* RESULT */}
      <Result/>
    </div>
  )
}
